### PR TITLE
Add Swiftlint

### PR DESCRIPTION
**Pull request by Onejjy**
Hey, 

As discussed in #28, here is an implementation of Swiftlint:

- SwiftLint runs on each sample project build (so you can see mistakes directly when coding)
- SwifLint is launched by Travis. So, if there is a major issue, it will break the build.
- I fixed some issues
- But lots of issues have been fixed by `swiftlint autocorrect`. 

Note that `swiftlint` only check files in `./Sources`. If you want to see results of lint into Xcode, you just have to install SwiftLint: `brew install swiftlint`

### CODE REVIEW

**Comment by Onejjy** [comment]
Here is an exemple of a travis build failed: https://travis-ci.org/Onejjy/DynamicColor/builds/179440974

**Comment by yannickl** [comment]
Great @Onejjy!

I'll merge it after a little update.

All my projects put the `else` or the `catch` statements on a new line instead of the same line. I've checked the SwiftLint documentation and we can support this code convention by setting the `statement_mode` to `uncuddled_else`.

**Comment by Onejjy** [comment]
@yannickl I updated the configuration file :). It should fix this.

**Comment by yannickl** [comment]
Awesome! I wanted to do this but I'm really busy for the moment. 👍

**Pull request merged**
