### PR TITLE
Add OS X support

### PR DESCRIPTION
**Pull request by duemunk**

### CODE REVIEW

**Comment by yannickl** [comment]
That's no so simple, it does not compile for OSX.

`UICColor` and `NSColor` are a bit different so you need to add some preprocessor guards.

**Comment by yannickl** [comment]
Here how to fix that:

```swift
  // MARK: - Getting the RGBA Components

  /**
  Returns the RGBA (red, green, blue, alpha) components.

  - returns: The RGBA components as a tuple (r, g, b, a).
  */
  public final func toRGBAComponents() -> (r: CGFloat, g: CGFloat, b: CGFloat, a: CGFloat) {
    var r: CGFloat = 0
    var g: CGFloat = 0
    var b: CGFloat = 0
    var a: CGFloat = 0

    #if os(iOS) || os(tvOS) || os(watchOS)
      if getRed(&r, green: &g, blue: &b, alpha: &a) {
        return (r, g, b, a)
      }

      return (0, 0, 0, 0)
    #elseif os(OSX)
      getRed(&r, green: &g, blue: &b, alpha: &a)

      return (r, g, b, a)
    #endif
  }

#if os(iOS) || os(tvOS) || os(watchOS)
  /**
  Returns the red component.
  
  - returns: The red component as CGFloat.
  */
  public final func redComponent() -> CGFloat {
    return toRGBAComponents().r
  }

  /**
  Returns the green component.

  - returns: The green component as CGFloat.
  */
  public final func greenComponent() -> CGFloat {
    return toRGBAComponents().g
  }

  /**
  Returns the blue component.

  - returns: The blue component as CGFloat.
  */
  public final func blueComponent() -> CGFloat {
    return toRGBAComponents().b
  }

  /**
  Returns the alpha component.

  - returns: The alpha component as CGFloat.
  */
  public final func alphaComponent() -> CGFloat {
    return toRGBAComponents().a
  }
#endif
```

**Comment by duemunk** [comment]
That's true. I've update with working code :)

**Comment by yannickl** [comment]
No probs. Thank you for the contribution! :+1:

**Pull request merged**
